<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeepTrack.Common\KeepTrack.Common.csproj" />
    <ProjectReference Include="..\KeepTrack.Modules\Employees\Employees.Infrastructure\Employees.Infrastructure.csproj" />
    <ProjectReference Include="..\KeepTrack.Modules\Executing\Executing.Infrastructure\Executing.Infrastructure.csproj" />
    <ProjectReference Include="..\KeepTrack.Modules\Identity\Authentication.Infastructure\Authentication.Infastructure.csproj" />
    <ProjectReference Include="..\Subscription.Infrastructure\SubscriptionAndPlan.Infrastructure.csproj" />
    <ProjectReference Include="..\KeepTrack.Modules\Tasks\Task.Infrastructure\Executing.Infrastructure.csproj" />
  </ItemGroup>

</Project>
